/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as PodcastBeyondTheBenchRouteImport } from './routes/podcast-beyond-the-bench'
import { Route as PeridioCoreRouteImport } from './routes/peridio-core'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as IndustryTelematicsRouteImport } from './routes/industry-telematics'
import { Route as IndustrySmarthomesRouteImport } from './routes/industry-smarthomes'
import { Route as IndustryIndustrialIotRouteImport } from './routes/industry-industrial-iot'
import { Route as IndustryHealthAndWearablesRouteImport } from './routes/industry-health-and-wearables'
import { Route as IndustryEnergyAndRenewablesRouteImport } from './routes/industry-energy-and-renewables'
import { Route as IndustryConsumerElectronicsRouteImport } from './routes/industry-consumer-electronics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as BookAMeetingRouteImport } from './routes/book-a-meeting'
import { Route as AvocadoOsRouteImport } from './routes/avocado-os'
import { Route as AiReadyRouteImport } from './routes/ai-ready'
import { Route as IndexRouteImport } from './routes/index'

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastBeyondTheBenchRoute = PodcastBeyondTheBenchRouteImport.update({
  id: '/podcast-beyond-the-bench',
  path: '/podcast-beyond-the-bench',
  getParentRoute: () => rootRouteImport,
} as any)
const PeridioCoreRoute = PeridioCoreRouteImport.update({
  id: '/peridio-core',
  path: '/peridio-core',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryTelematicsRoute = IndustryTelematicsRouteImport.update({
  id: '/industry-telematics',
  path: '/industry-telematics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySmarthomesRoute = IndustrySmarthomesRouteImport.update({
  id: '/industry-smarthomes',
  path: '/industry-smarthomes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryIndustrialIotRoute = IndustryIndustrialIotRouteImport.update({
  id: '/industry-industrial-iot',
  path: '/industry-industrial-iot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryHealthAndWearablesRoute =
  IndustryHealthAndWearablesRouteImport.update({
    id: '/industry-health-and-wearables',
    path: '/industry-health-and-wearables',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustryEnergyAndRenewablesRoute =
  IndustryEnergyAndRenewablesRouteImport.update({
    id: '/industry-energy-and-renewables',
    path: '/industry-energy-and-renewables',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustryConsumerElectronicsRoute =
  IndustryConsumerElectronicsRouteImport.update({
    id: '/industry-consumer-electronics',
    path: '/industry-consumer-electronics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAMeetingRoute = BookAMeetingRouteImport.update({
  id: '/book-a-meeting',
  path: '/book-a-meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const AvocadoOsRoute = AvocadoOsRouteImport.update({
  id: '/avocado-os',
  path: '/avocado-os',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReadyRoute = AiReadyRouteImport.update({
  id: '/ai-ready',
  path: '/ai-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-ready': typeof AiReadyRoute
  '/avocado-os': typeof AvocadoOsRoute
  '/book-a-meeting': typeof BookAMeetingRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/industry-consumer-electronics': typeof IndustryConsumerElectronicsRoute
  '/industry-energy-and-renewables': typeof IndustryEnergyAndRenewablesRoute
  '/industry-health-and-wearables': typeof IndustryHealthAndWearablesRoute
  '/industry-industrial-iot': typeof IndustryIndustrialIotRoute
  '/industry-smarthomes': typeof IndustrySmarthomesRoute
  '/industry-telematics': typeof IndustryTelematicsRoute
  '/partners': typeof PartnersRoute
  '/peridio-core': typeof PeridioCoreRoute
  '/podcast-beyond-the-bench': typeof PodcastBeyondTheBenchRoute
  '/ui': typeof UiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-ready': typeof AiReadyRoute
  '/avocado-os': typeof AvocadoOsRoute
  '/book-a-meeting': typeof BookAMeetingRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/industry-consumer-electronics': typeof IndustryConsumerElectronicsRoute
  '/industry-energy-and-renewables': typeof IndustryEnergyAndRenewablesRoute
  '/industry-health-and-wearables': typeof IndustryHealthAndWearablesRoute
  '/industry-industrial-iot': typeof IndustryIndustrialIotRoute
  '/industry-smarthomes': typeof IndustrySmarthomesRoute
  '/industry-telematics': typeof IndustryTelematicsRoute
  '/partners': typeof PartnersRoute
  '/peridio-core': typeof PeridioCoreRoute
  '/podcast-beyond-the-bench': typeof PodcastBeyondTheBenchRoute
  '/ui': typeof UiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-ready': typeof AiReadyRoute
  '/avocado-os': typeof AvocadoOsRoute
  '/book-a-meeting': typeof BookAMeetingRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/industry-consumer-electronics': typeof IndustryConsumerElectronicsRoute
  '/industry-energy-and-renewables': typeof IndustryEnergyAndRenewablesRoute
  '/industry-health-and-wearables': typeof IndustryHealthAndWearablesRoute
  '/industry-industrial-iot': typeof IndustryIndustrialIotRoute
  '/industry-smarthomes': typeof IndustrySmarthomesRoute
  '/industry-telematics': typeof IndustryTelematicsRoute
  '/partners': typeof PartnersRoute
  '/peridio-core': typeof PeridioCoreRoute
  '/podcast-beyond-the-bench': typeof PodcastBeyondTheBenchRoute
  '/ui': typeof UiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-ready'
    | '/avocado-os'
    | '/book-a-meeting'
    | '/company'
    | '/contact'
    | '/industry-consumer-electronics'
    | '/industry-energy-and-renewables'
    | '/industry-health-and-wearables'
    | '/industry-industrial-iot'
    | '/industry-smarthomes'
    | '/industry-telematics'
    | '/partners'
    | '/peridio-core'
    | '/podcast-beyond-the-bench'
    | '/ui'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-ready'
    | '/avocado-os'
    | '/book-a-meeting'
    | '/company'
    | '/contact'
    | '/industry-consumer-electronics'
    | '/industry-energy-and-renewables'
    | '/industry-health-and-wearables'
    | '/industry-industrial-iot'
    | '/industry-smarthomes'
    | '/industry-telematics'
    | '/partners'
    | '/peridio-core'
    | '/podcast-beyond-the-bench'
    | '/ui'
  id:
    | '__root__'
    | '/'
    | '/ai-ready'
    | '/avocado-os'
    | '/book-a-meeting'
    | '/company'
    | '/contact'
    | '/industry-consumer-electronics'
    | '/industry-energy-and-renewables'
    | '/industry-health-and-wearables'
    | '/industry-industrial-iot'
    | '/industry-smarthomes'
    | '/industry-telematics'
    | '/partners'
    | '/peridio-core'
    | '/podcast-beyond-the-bench'
    | '/ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiReadyRoute: typeof AiReadyRoute
  AvocadoOsRoute: typeof AvocadoOsRoute
  BookAMeetingRoute: typeof BookAMeetingRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  IndustryConsumerElectronicsRoute: typeof IndustryConsumerElectronicsRoute
  IndustryEnergyAndRenewablesRoute: typeof IndustryEnergyAndRenewablesRoute
  IndustryHealthAndWearablesRoute: typeof IndustryHealthAndWearablesRoute
  IndustryIndustrialIotRoute: typeof IndustryIndustrialIotRoute
  IndustrySmarthomesRoute: typeof IndustrySmarthomesRoute
  IndustryTelematicsRoute: typeof IndustryTelematicsRoute
  PartnersRoute: typeof PartnersRoute
  PeridioCoreRoute: typeof PeridioCoreRoute
  PodcastBeyondTheBenchRoute: typeof PodcastBeyondTheBenchRoute
  UiRoute: typeof UiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast-beyond-the-bench': {
      id: '/podcast-beyond-the-bench'
      path: '/podcast-beyond-the-bench'
      fullPath: '/podcast-beyond-the-bench'
      preLoaderRoute: typeof PodcastBeyondTheBenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peridio-core': {
      id: '/peridio-core'
      path: '/peridio-core'
      fullPath: '/peridio-core'
      preLoaderRoute: typeof PeridioCoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-telematics': {
      id: '/industry-telematics'
      path: '/industry-telematics'
      fullPath: '/industry-telematics'
      preLoaderRoute: typeof IndustryTelematicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-smarthomes': {
      id: '/industry-smarthomes'
      path: '/industry-smarthomes'
      fullPath: '/industry-smarthomes'
      preLoaderRoute: typeof IndustrySmarthomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-industrial-iot': {
      id: '/industry-industrial-iot'
      path: '/industry-industrial-iot'
      fullPath: '/industry-industrial-iot'
      preLoaderRoute: typeof IndustryIndustrialIotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-health-and-wearables': {
      id: '/industry-health-and-wearables'
      path: '/industry-health-and-wearables'
      fullPath: '/industry-health-and-wearables'
      preLoaderRoute: typeof IndustryHealthAndWearablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-energy-and-renewables': {
      id: '/industry-energy-and-renewables'
      path: '/industry-energy-and-renewables'
      fullPath: '/industry-energy-and-renewables'
      preLoaderRoute: typeof IndustryEnergyAndRenewablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry-consumer-electronics': {
      id: '/industry-consumer-electronics'
      path: '/industry-consumer-electronics'
      fullPath: '/industry-consumer-electronics'
      preLoaderRoute: typeof IndustryConsumerElectronicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-meeting': {
      id: '/book-a-meeting'
      path: '/book-a-meeting'
      fullPath: '/book-a-meeting'
      preLoaderRoute: typeof BookAMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avocado-os': {
      id: '/avocado-os'
      path: '/avocado-os'
      fullPath: '/avocado-os'
      preLoaderRoute: typeof AvocadoOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ready': {
      id: '/ai-ready'
      path: '/ai-ready'
      fullPath: '/ai-ready'
      preLoaderRoute: typeof AiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiReadyRoute: AiReadyRoute,
  AvocadoOsRoute: AvocadoOsRoute,
  BookAMeetingRoute: BookAMeetingRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  IndustryConsumerElectronicsRoute: IndustryConsumerElectronicsRoute,
  IndustryEnergyAndRenewablesRoute: IndustryEnergyAndRenewablesRoute,
  IndustryHealthAndWearablesRoute: IndustryHealthAndWearablesRoute,
  IndustryIndustrialIotRoute: IndustryIndustrialIotRoute,
  IndustrySmarthomesRoute: IndustrySmarthomesRoute,
  IndustryTelematicsRoute: IndustryTelematicsRoute,
  PartnersRoute: PartnersRoute,
  PeridioCoreRoute: PeridioCoreRoute,
  PodcastBeyondTheBenchRoute: PodcastBeyondTheBenchRoute,
  UiRoute: UiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
